version: "3.9"

services:
  db:
    image: postgres:15
    container_name: expense_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
