version: "3.9"

services:
  db:
    image: postgres:15
    container_name: expense_postgres
    restart: always
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    container_name: expense_api
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://expense_user:expense_pass@db:5432/expense_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
